language: r
cache:
- packages
- pip
install:
- pip install --user pandocfilters pandoc-crossref
- tlmgr install setspace times
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
script:
- cd source
- mkdir _build
- pandoc manuscript.md _metadata.yml --lua-filter=../filters/include-files.lua -F pandoc-crossref --citeproc --lua-filter=../filters/scholarly-metadata.lua --lua-filter=../filters/author-info-blocks.lua --lua-filter ../filters/pagebreak.lua -o _build/manuscript.pdf
- pandoc manuscript.md _metadata.yml --lua-filter=../filters/include-files.lua -F pandoc-crossref --citeproc --lua-filter=../filters/scholarly-metadata.lua --lua-filter=../filters/author-info-blocks.lua --lua-filter ../filters/pagebreak.lua -o _build/manuscript.docx
deploy:
  provider: releases
  api_key:
    secure: PF7uyRuv84GJgs7mxAqmpRa8U2fLB9PZtF3jiTgzI6EfDZHk06XsIvLp1oQB9qxWRoJXR3Q0FOI4alMhN3FoszVjqwMzkQ3VSmOhYtHc37Ko1Zql0cWJof2CpljIzzGvhD08K+oYQsTZLuCluN6ri6WxCLKRDK/2rt7fFqDhLKh/iAzazpYY0rdd1wdO5iEoWlLbJ3UAJhHNgY9L/Tp4I2yIgm44P1HX+FIYhjdaj3SR4I9Z57CzIF03pxSa33ItAfRJtUG6UNS67H2JsGmteLwcLBVC9KV41IR6n+jlwbYLPwkfYsNpKvB7cyBGnu3iOx+QG2uLXCzlYab8qVvQNhWq7egAORCGrmw/23LlCX94hYzTNg9kKNPv3cVJ8jWRYTojGFHOjKpnwPrdxu+qTIzA6XB+zkO6wPxvllf69qVQ9aLaqB6E2CLsoiYyCEBVP6iaelUzCbX8JmIZIuZ36IdHmbv0x2DKgSxbOC21zoQT7adE6piovyaNRniJAQoIFF4kYhNYv8tgfk4NcuVXSO27GcSXTozXyeAV7t+67U0fXjXirnOboTa07dJNE78kSXBL6w9Y52vPxqsHmH7NKPIMbeXq+33A7VSFMxH9t+DD0Xo1PUHx4ZCTNFGapEPQzxkfgytL5871MKqXLE275pg22uSRMmwYymkmAL9ef6I=
  file:
    - "_build/manuscript.pdf"
    - "_build/manuscript.docx"
  skip_cleanup: true
  draft: true
  on:
    repo: mitchellmcm27/pandoc-manuscript-starter
