
language: r
cache:
  - packages
  - pip
install:
  - pip install --user pandocfilters pandoc-fignos pandoc-eqnos
  - tlmgr install setspace times
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
    -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
script:
  - mkdir _build
  - pandoc ./source/manuscript.md 
  --filter pandoc-eqnos 
  --filter pandoc-fignos 
  --filter pandoc-citeproc 
  -o _build/manuscript.pdf
deploy:
  provider: releases
  api_key:
    secure: "GITHUB OAUTH TOKEN"
  file: "_build/manuscript.pdf"
  skip_cleanup: true
  draft: true
