language: r
cache:
- packages
- pip
install:
- pip install --user pandocfilters pandoc-fignos pandoc-eqnos
- tlmgr install setspace times
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
script:
- cd source
- mkdir _build
- pandoc manuscript.md -F pandoc-eqnos -F pandoc-fignos -F pandoc-citeproc -o _build/manuscript.pdf
deploy:
  provider: releases
  api_key:
    secure: JrM7WlwiNSqqr5ctcHeodBUgyR2gXDVMg+swVPbDe+oHYMxRtgM7GVcTVLDnUx1Z5cjOVvz5DfqWWxlWULF6MwsEc5Lm5xHL812cOMxFreVJJZty5HIKUarmG4Q2VLzDpJ14NqqUDBqAo3qHlAjjW3Gt7mVv6tWeZTdG9zaiho2danUU33eMMxmjI2Hl6oe3T1HZs1k3+x4UegXSk1NaE1cTpuKRupLaaGs8mU5SFy9cd4SzN/hRd6LSY5sSTA7YAsDAnB9BdAcHOLrjporOCcq7aWhTd74ZT/iQg+lgQ0sDIbkUQZ8qV8zeAM1PL6s2YVzzCJvqyn4ndkKOA0Jtta4Ms0PJP5xL1Cf9P7xYN38t9OnLnL5slKTGOwFNLg9MVqai/q+SoQDVjfp+hSi4u8nEw/2k1QXoH/PzEK2LgdnP+v6O8e3ZywwMG0m0BoDxPrBNmkp1u+t0cFq/L9gILI/8cUpctfmqd7EABaePEPscPxvbIpNffixKRXhPSiqtu0b4/RxKjMDm27JlT7h6/e5LgScqFoJFOfArcTPrqJafnHlV8Wubj8ZmGiHqe9LEYgQD68+x7uu3XX7e51X6KnqxBur+WsY+z43XfZPac5Exd4nxNv06zOWQw/NZSYItZegSjbpQZhx79yIhgOQRMGVt3wgp8Xyko2/mP7r0Td0=
  file: _build/manuscript.pdf
  skip_cleanup: true
  draft: true