language: r
cache:
- packages
- pip
install:
- pip install --user pandocfilters pandoc-fignos pandoc-eqnos
- tlmgr install setspace times
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
script:
- cd source
- mkdir _build
- pandoc manuscript.md -F pandoc-eqnos -F pandoc-fignos -F pandoc-citeproc -o _build/manuscript.pdf
deploy:
  provider: releases
  api_key:
    secure: ZZ2L2MQMhyZVr+ycsNe2j5J2PgYiZB4mGpdfJJdk8/UTC4BcBhSliUig2VbUX+mSp1iuuxzSVdV7Ktwr+PSHirxrE8eC2NZDObXNYdMjOC97Gj9D+XwzRIgp2EgPflAj4OZL7rQz93lizjsXANAFt0bg61dXPmipH03sMrBEf3/F+dhAUL0dEUXxhdD+6WNeVry+I1p+UQ+U5W1TIfHPs0T6pQabSeKAfdgnrLgh8gBqdM/yQs2isXoSmnctw1/KGgt7Kxh5JoHT9W/P5wDN5Ix8RB4tISnQe8+nRsIqVi+fTxkhx86/pibNW13q+ggdTflQ589GErNtZmgkx9I+D0jehlWWOdTx3cBpp9lhl4fTcPBio5n5yPPIn0AqSse8qxab/M0GUTJH5FQuBtte6bEqHpZ7kNUcJQ0r5Lns1BXrmJ8h6u9Da/2kmpOudq7oTPG4JBGat6k9ZbJr3iCMq/T3jAKfo1bbmkebBmPab9DdKEnbhGbNr8xtEAvSdUTFzk6rCDSfnAq+NwNaBHj3hQPLQWgxdFth3dDlqmmNYOhRsYDojO3p+OfsqC4fVzawLVjhXjs9C1qqJuBoVaz4EyiOY11ui7JiCSR7WwPAhjM8dKrt1wjs8rWil73dgi57jSjyNFsxqANolOqSDzRyv3hvnt+eIhOzdJffMF2lN7g=
  file: _build/manuscript.pdf
  skipe_cleanup: true
  draft: true