
language: r
cache:
  - packages
  - pip
install:
  - pip install --user pandocfilters
  - tlmgr install setspace times
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
    -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
script:
  - mkdir _build
  - pandoc manuscript.md --filter pandoc-citeproc -o _build/manuscript.pdf
deploy:
  provider: releases
  api_key:
    secure: [API KEY]
  file: "_build/manuscript.pdf"
  skip_cleanup: true
  on:
    tags: true
