name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/latex:2.16.1
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=output/manuscript.pdf
            source/manuscript.md
            _metadata.yml
            --lua-filter=filters/include-files.lua 
            -F pandoc-crossref 
            --citeproc 
            --lua-filter=filters/scholarly-metadata.lua 
            --lua-filter=filters/author-info-blocks.lua 
            --lua-filter=filters/pagebreak.lua
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
