name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/latex:2.16.1
    steps:
      - uses: actions/checkout@v2
      - run: |
          tlmgr install cleveref siunitx
      - run: |
          pandoc --standalone --output=manuscript.pdf source/manuscript.md source/_metadata.yml --lua-filter=./filters/include-files.lua  -F pandoc-crossref --citeproc --lua-filter=./filters/scholarly-metadata.lua --lua-filter=./filters/author-info-blocks.lua --lua-filter=./filters/pagebreak.lua --csl=styles/american-geophysical-union.csl --bibliography=source/library.bib
      - uses: actions/upload-artifact@master
        with:
          name: manuscript.pdf
          path: manuscript.pdf
